### ISSUE TITLE
qustion about runtimeError

### ISSUE THREAD

**Issue by eunkyungYoo** [ByungKwanLee/MoAI#23]
Hello, 

I had a runtime error as below. I couldn't find a solution. 
Could you check this issue?

Thank you. 

MMCV: 2.0.0rc4
CUDA : cu118
MMDetection: 3.3.0
torch : 2.0.1+cu118

=============
Traceback (most recent call last):
  File "/app/data/moai/demo.py", line 21, in <module>
    = prepare_moai(moai_path='BK-Lee/MoAI-7B', bits=4, grad_ckpt=False, lora=False, dtype='fp16')
  File "/app/data/moai/moai/load_moai.py", line 60, in prepare_moai
    param.requires_grad_(True)
RuntimeError: only Tensors of floating point dtype can require gradients

**Comment by eunkyungYoo** [comment]
I fixed the issue by changing the PaddleOCR and Transformers versions.
